# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-18 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='mode',
            field=models.PositiveSmallIntegerField(choices=[(1, '系统所有'), (2, '本机构及下属机构'), (3, '本机构'), (4, '本部门及下属部门'), (5, '本部门'), (6, '仅本人')], default=6, verbose_name='数据授权模式'),
        ),
    ]
