# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-09-20 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='角色组名称')),
            ],
        ),
        migrations.AlterModelOptions(
            name='roleresourceassign',
            options={'verbose_name': '角色的权限', 'verbose_name_plural': '角色的权限'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '系统用户', 'verbose_name_plural': '系统用户'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='org',
        ),
        migrations.AddField(
            model_name='role',
            name='role_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '总管理员'), (2, '分管理员'), (3, '主管'), (4, '普通角色')], default=4, verbose_name='角色类型'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='head_img',
            field=models.ImageField(default='default.png', upload_to=users.models.UserProfile.gen_image_name, verbose_name='用户头像'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_avatar',
            field=models.BooleanField(default=True, verbose_name='导航栏显示头像'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_tagsview',
            field=models.BooleanField(default=True, verbose_name='开启页签模式'),
        ),
        migrations.AddField(
            model_name='webresource',
            name='code_link',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='快查链接'),
        ),
        migrations.AddField(
            model_name='webresource',
            name='component',
            field=models.CharField(default='login/Login', max_length=300, verbose_name='前端组件'),
        ),
        migrations.AddField(
            model_name='webresource',
            name='component_name',
            field=models.CharField(default='Login', max_length=100, verbose_name='前端组件名称'),
        ),
        migrations.AddField(
            model_name='webresource',
            name='icon',
            field=models.CharField(default='tree-table', max_length=100, verbose_name='前端图标'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='code_link',
            field=models.CharField(default=uuid.UUID('fe245445-ce09-4901-aaa7-f081aa0f844a'), max_length=2000, verbose_name='快查链接'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='code_name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='公司域名'),
        ),
        migrations.AlterField(
            model_name='role',
            name='mode',
            field=models.PositiveSmallIntegerField(choices=[(1, '系统所有'), (2, '本机构及下属'), (3, '仅本机构'), (4, '本部门及下属'), (5, '仅本部门'), (6, '仅本人')], default=6, verbose_name='授权范围'),
        ),
        migrations.AlterField(
            model_name='role',
            name='resource',
            field=models.ManyToManyField(through='users.RoleResourceAssign', to='users.WebResource', verbose_name='角色的菜单'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dept',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dept',
            field=models.ManyToManyField(related_name='dept_user', to='users.Organization', verbose_name='用户组织'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ManyToManyField(related_name='role_user', to='users.Role', verbose_name='用户角色'),
        ),
        migrations.AlterField(
            model_name='webresource',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.WebResource', verbose_name='父级权限'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='role',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='role',
            name='org',
        ),
    ]
