# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-18 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200318_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='webresource',
            name='code_link',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='快查链接'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='code_link',
            field=models.CharField(max_length=2000, verbose_name='快查链接'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='code_name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='公司域名'),
        ),
        migrations.AlterField(
            model_name='role',
            name='mode',
            field=models.PositiveSmallIntegerField(choices=[(1, '系统所有'), (2, '本机构及下属'), (3, '仅本机构'), (4, '本部门及下属'), (5, '仅本部门'), (6, '仅本人')], default=6, verbose_name='数据授权模式'),
        ),
    ]
