# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-09-20 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200920_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='code_link',
            field=models.CharField(default=uuid.UUID('c42f7224-0009-4269-a8f3-bf7947e0422f'), max_length=2000, verbose_name='快查链接'),
        ),
    ]
